name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Create pull request -> develop
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm run format:check
      - run: npm test -- --coverage
        env:
          CI: true

      # Confirm pull request
      - name: Build and Deploy
        if: github.event_name == 'push'
        run: npm run deploy
